DROP TABLE IF EXISTS "lesson_completions" CASCADE;
DROP TABLE IF EXISTS "exercises" CASCADE;
DROP TABLE IF EXISTS "lessons" CASCADE;
DROP TABLE IF EXISTS "courses" CASCADE;
DROP TABLE IF EXISTS "programming_languages" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;
CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "programming_languages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL
);
CREATE TABLE "courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "description" text
);
CREATE TABLE "lessons" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "theory" text,
  "sort_order" int NOT NULL,
  "xp_reward" int NOT NULL DEFAULT 10
);
CREATE TABLE "exercises" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "type" varchar NOT NULL,
  "payload" jsonb NOT NULL,
  "sort_order" int NOT NULL,
  CONSTRAINT exercises_type_check CHECK (type IN ('choice', 'input'))
);
CREATE TABLE "lesson_completions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "completed_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "score" int
);
ALTER TABLE "courses"
ADD CONSTRAINT courses_language_fk FOREIGN KEY ("language_id") REFERENCES "programming_languages" ("id") ON DELETE CASCADE;
ALTER TABLE "lessons"
ADD CONSTRAINT lessons_course_fk FOREIGN KEY ("course_id") REFERENCES "courses" ("id") ON DELETE CASCADE;
ALTER TABLE "exercises"
ADD CONSTRAINT exercises_lesson_fk FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE;
ALTER TABLE "lesson_completions"
ADD CONSTRAINT lesson_completions_user_fk FOREIGN KEY ("user_id") REFERENCES "users" ("id") ON DELETE CASCADE;
ALTER TABLE "lesson_completions"
ADD CONSTRAINT lesson_completions_lesson_fk FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") ON DELETE CASCADE;
CREATE INDEX idx_lessons_course ON "lessons" ("course_id", "sort_order");
CREATE INDEX idx_exercises_lesson ON "exercises" ("lesson_id", "sort_order");
CREATE INDEX idx_completions_user ON "lesson_completions" ("user_id");
