-- for create tables and relationships

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar UNIQUE NOT NULL,
  "username" varchar UNIQUE NOT NULL,
  "password_hash" varchar NOT NULL,
  "created_at" timestamp NOT NULL
);

CREATE TABLE "programming_languages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "code" varchar UNIQUE NOT NULL
);

CREATE TABLE "courses" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "language_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "description" text
);

CREATE TABLE "lessons" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "course_id" bigint NOT NULL,
  "title" varchar NOT NULL,
  "theory" text,
  "sort_order" int NOT NULL,
  "xp_reward" int NOT NULL DEFAULT 10
);

CREATE TABLE "exercises" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lesson_id" bigint NOT NULL,
  "type" varchar NOT NULL,
  "question" text NOT NULL,
  "correct_answer" text NOT NULL,
  "sort_order" int NOT NULL
);

CREATE TABLE "lesson_completions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint NOT NULL,
  "lesson_id" bigint NOT NULL,
  "completed_at" timestamp NOT NULL,
  "score" int
);

ALTER TABLE "courses" ADD FOREIGN KEY ("language_id") REFERENCES "programming_languages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lessons" ADD FOREIGN KEY ("course_id") REFERENCES "courses" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "exercises" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_completions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lesson_completions" ADD FOREIGN KEY ("lesson_id") REFERENCES "lessons" ("id") DEFERRABLE INITIALLY IMMEDIATE;
